[dependencies]
espresso-logic = "3.1.2"
logic-hf-core.workspace = true

[package]
edition = "2024"
name = "logic-hf"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
